version: '3.8'

networks:
  default:
    name: web

services:
  app:
    container_name: mdolnicek_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  nginx:
    container_name: mdolnicek_nginx
    image: nginx:alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    depends_on:
      - app