version: '3.8'

networks:
  default:
      name: web

services:
  app:
    container_name: mdolnicek_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  nginx:
    container_name: mdolnicek_nginx
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mdolnicek.rule=Host(`mdolnicek.localhost`)"
      - "traefik.http.routers.mdolnicek.entrypoints=web"
    networks:
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - app